"""``naming`` rule pack — naming-case rules for protokit-lint.

D2 shipped the AIP-122 field-naming canary (``naming/snake-case-fields``).
D6a (Unit 3) extends the pack with the remaining naming-case rules
needed for buf BASIC parity: PascalCase for messages/enums/services/RPCs;
UPPER_SNAKE_CASE for enum values; lower_snake for oneofs/files/packages.

References:
- AIP-122 § "Field names":
  https://google.aip.dev/122
- buf BASIC rule catalog (parity targets named per-rule via
  ``source_spec="buf:<RULE_ID>"``).
- protokit-lint D2 plan:
  ``docs/plans/2026-05-02-001-feat-protokit-lint-d2-engine-plan.md``
- protokit-lint D6a plan:
  ``docs/plans/2026-05-12-001-feat-protokit-lint-d6a-rule-library-plan.md``

Module shape adopts the ``RULES`` attribute name from compat
(``schema/checker.py:217-220``) but its wire format differs: this
pack's ``RULES`` is a tuple of bare ``@lint_rule``-decorated
functions (the rule_id lives on ``fn._lint_spec``), whereas compat's
``RULES`` is ``(rule_id, plugin_fn)`` tuples. Lint packs cannot be
loaded into ``SchemaChecker`` and vice versa; the divergence is
documented in ``LintEngine.load_rule_pack``'s docstring.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from pathlib import PurePosixPath
from typing import TYPE_CHECKING

from protokit.schema.lint.decorator import lint_rule
from protokit.schema.lint.model import ElementKind, LintSeverity

if TYPE_CHECKING:
    from protokit.schema.lint.model import (
        EnumLintContext,
        EnumValueLintContext,
        FieldLintContext,
        FileLintContext,
        MessageLintContext,
        MethodLintContext,
        OneofLintContext,
        ServiceLintContext,
    )


# AIP-122 snake_case: lowercase start, alphanumeric segments separated
# by single underscores. Rejects: BadCamelCase (uppercase),
# with__double (consecutive underscores), trailing_ (trailing
# underscore), with-dash (non-word character), UPPER (uppercase).
# Note: protobuf grammar already rejects leading-underscore field
# names at the source level; the regex would also reject them, but
# in practice that branch is dead.
_SNAKE_CASE_RE = re.compile(r"^[a-z][a-z0-9]*(_[a-z0-9]+)*$")

# PascalCase: an uppercase letter followed by zero or more alphanumeric
# characters. Matches buf's MESSAGE_PASCAL_CASE / ENUM_PASCAL_CASE /
# SERVICE_PASCAL_CASE / RPC_PASCAL_CASE which accept single-letter names
# (``A``), all-uppercase acronyms (``URL``), and mixed (``UserService``).
# Rejects: lowercase-leading (``userService``), embedded underscores
# (``User_v2``), leading underscore (``_Foo``).
_PASCAL_CASE_RE = re.compile(r"^[A-Z][A-Za-z0-9]*$")

# UPPER_SNAKE_CASE: uppercase-leading segment, alphanumeric uppercase
# segments separated by single underscores. Matches ``STATUS``,
# ``STATUS_ACTIVE``, ``STATUS_V2``. Rejects mixed-case
# (``StatusActive``, ``STATUS_active``), trailing underscore.
_UPPER_SNAKE_CASE_RE = re.compile(r"^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$")


@lint_rule(
    rule_id="naming/snake-case-fields",
    severity=LintSeverity.WARNING,
    profiles=("recommended", "default"),
    element=ElementKind.FIELD,
    message_template="Field {name!r} is not snake_case (AIP-122)",
    source_spec="https://google.aip.dev/122",
)
def check_snake_case_fields(ctx: FieldLintContext) -> None:
    """Fire on field names that don't match AIP-122 snake_case.

    Skips the synthetic ``key`` / ``value`` fields generated inside
    protobuf map-entry messages: their names are pre-defined by the
    protobuf compiler from ``map<K, V>`` declarations and are not
    user-authored, so a snake_case warning would be noise. The
    detection is on the field's containing type (the entry message
    has ``map_entry = true`` set in its options); the user-facing
    map field itself (e.g., ``attributes`` in
    ``map<string, string> attributes = 1;``) IS user-authored and
    IS linted normally.

    Profile membership widened in D6a Unit 3 from ``("default",)`` to
    ``("recommended", "default")`` — the canary joins the buf-parity
    rule set rather than living as a "default only" warning.
    """
    if ctx.field.containing_type.GetOptions().map_entry:
        return
    if not _SNAKE_CASE_RE.match(ctx.field.name):
        ctx.emit(
            violation_kind="naming/snake-case-fields",
            params={"name": ctx.field.name},
        )


@lint_rule(
    rule_id="naming/pascal-case-messages",
    severity=LintSeverity.ERROR,
    profiles=("recommended", "default"),
    element=ElementKind.MESSAGE,
    message_template="Message {name!r} is not PascalCase",
    source_spec="buf:MESSAGE_PASCAL_CASE",
)
def check_pascal_case_messages(ctx: MessageLintContext) -> None:
    """Fire on message names that don't match PascalCase.

    Skips synthetic map-entry messages (``<FieldName>Entry`` types
    auto-generated by the protobuf compiler from ``map<K, V>``
    declarations). These names ARE PascalCase by convention, but
    skipping the descriptor-pool-synthesized type entirely avoids
    coupling the rule's correctness to compiler naming choices and
    mirrors the canary's map-entry skip discipline.
    """
    if ctx.message.GetOptions().map_entry:
        return
    if not _PASCAL_CASE_RE.match(ctx.message.name):
        ctx.emit(
            violation_kind="naming/pascal-case-messages",
            params={"name": ctx.message.name},
        )


@lint_rule(
    rule_id="naming/pascal-case-enums",
    severity=LintSeverity.ERROR,
    profiles=("recommended", "default"),
    element=ElementKind.ENUM,
    message_template="Enum {name!r} is not PascalCase",
    source_spec="buf:ENUM_PASCAL_CASE",
)
def check_pascal_case_enums(ctx: EnumLintContext) -> None:
    """Fire on enum names that don't match PascalCase."""
    if not _PASCAL_CASE_RE.match(ctx.enum.name):
        ctx.emit(
            violation_kind="naming/pascal-case-enums",
            params={"name": ctx.enum.name},
        )


@lint_rule(
    rule_id="naming/upper-snake-case-enum-values",
    severity=LintSeverity.ERROR,
    profiles=("recommended", "default"),
    element=ElementKind.ENUM_VALUE,
    message_template="Enum value {name!r} is not UPPER_SNAKE_CASE",
    source_spec="buf:ENUM_VALUE_UPPER_SNAKE_CASE",
)
def check_upper_snake_case_enum_values(ctx: EnumValueLintContext) -> None:
    """Fire on enum value names that don't match UPPER_SNAKE_CASE."""
    if not _UPPER_SNAKE_CASE_RE.match(ctx.value.name):
        ctx.emit(
            violation_kind="naming/upper-snake-case-enum-values",
            params={"name": ctx.value.name},
        )


@lint_rule(
    rule_id="naming/snake-case-oneofs",
    severity=LintSeverity.ERROR,
    profiles=("recommended", "default"),
    element=ElementKind.ONEOF,
    message_template="Oneof {name!r} is not snake_case",
    source_spec="buf:ONEOF_LOWER_SNAKE_CASE",
)
def check_snake_case_oneofs(ctx: OneofLintContext) -> None:
    """Fire on oneof names that don't match snake_case.

    Skips proto3 synthetic oneofs generated by ``optional`` fields.
    The protobuf compiler synthesizes a wrapper oneof for each
    ``optional <type> <name>`` declaration and names it
    ``_<field-name>``. The leading underscore is a reliable
    discriminator because protobuf grammar prohibits user-authored
    oneof names from starting with an underscore: any oneof whose
    name begins with ``_`` is therefore compiler-synthesized rather
    than user-declared, and a snake_case finding on the synthetic
    name would be a false positive on a common proto3 idiom. This
    matches buf's ONEOF_LOWER_SNAKE_CASE which similarly excludes
    synthetic oneofs from its check.
    """
    if ctx.oneof.name.startswith("_"):
        return
    if not _SNAKE_CASE_RE.match(ctx.oneof.name):
        ctx.emit(
            violation_kind="naming/snake-case-oneofs",
            params={"name": ctx.oneof.name},
        )


@lint_rule(
    rule_id="naming/pascal-case-services",
    severity=LintSeverity.ERROR,
    profiles=("recommended", "default"),
    element=ElementKind.SERVICE,
    message_template="Service {name!r} is not PascalCase",
    source_spec="buf:SERVICE_PASCAL_CASE",
)
def check_pascal_case_services(ctx: ServiceLintContext) -> None:
    """Fire on service names that don't match PascalCase."""
    if not _PASCAL_CASE_RE.match(ctx.service.name):
        ctx.emit(
            violation_kind="naming/pascal-case-services",
            params={"name": ctx.service.name},
        )


@lint_rule(
    rule_id="naming/pascal-case-rpcs",
    severity=LintSeverity.ERROR,
    profiles=("recommended", "default"),
    element=ElementKind.METHOD,
    message_template="RPC {name!r} is not PascalCase",
    source_spec="buf:RPC_PASCAL_CASE",
)
def check_pascal_case_rpcs(ctx: MethodLintContext) -> None:
    """Fire on RPC (service-method) names that don't match PascalCase."""
    if not _PASCAL_CASE_RE.match(ctx.method.name):
        ctx.emit(
            violation_kind="naming/pascal-case-rpcs",
            params={"name": ctx.method.name},
        )


@lint_rule(
    rule_id="naming/snake-case-files",
    severity=LintSeverity.ERROR,
    profiles=("recommended", "default"),
    element=ElementKind.FILE,
    message_template="File basename {name!r} is not snake_case",
    source_spec="buf:FILE_LOWER_SNAKE_CASE",
)
def check_snake_case_files(ctx: FileLintContext) -> None:
    """Fire on .proto file basenames that don't match snake_case.

    Checks the file's basename only (the directory portion is
    ignored); ``acme/v1/Foo_Bar.proto`` fires on the stem
    ``Foo_Bar``, ``acme/v1/foo_bar.proto`` is clean. Uses
    ``PurePosixPath`` so the rule produces identical results
    regardless of the host platform — proto file names recorded in
    the descriptor pool use POSIX separators by protobuf convention.

    Multi-dot filenames (e.g., ``acme.v1.proto``) resolve to a stem
    containing the inner dot (``acme.v1``) because ``PurePosixPath``
    strips only the final extension. The dot is not in the
    ``_SNAKE_CASE_RE`` character class, so such filenames fire. This
    matches buf's FILE_LOWER_SNAKE_CASE behavior: a ``.proto`` file
    is expected to have a single dot before its extension. Users
    encoding version segments in the filename should put them in
    the directory path (e.g., ``acme/v1/users.proto``) rather than
    the basename.
    """
    stem = PurePosixPath(ctx.file.name).stem
    if not _SNAKE_CASE_RE.match(stem):
        ctx.emit(
            violation_kind="naming/snake-case-files",
            params={"name": stem},
        )


@lint_rule(
    rule_id="naming/snake-case-packages",
    severity=LintSeverity.ERROR,
    profiles=("recommended", "default"),
    element=ElementKind.FILE,
    message_template=(
        "Package {package!r} has segment {segment!r} that is not snake_case"
    ),
    source_spec="buf:PACKAGE_LOWER_SNAKE_CASE",
)
def check_snake_case_packages(ctx: FileLintContext) -> None:
    """Fire on package segments that don't match snake_case.

    Splits ``ctx.file.package`` on ``.`` and checks each segment.
    A missing-package file (empty ``package``) is the concern of
    the separate ``package/defined`` rule (D6a Unit 6) and is
    skipped here — this rule speaks only to the case-shape of
    declared segments. Multi-segment packages fire one finding per
    offending segment so the report enumerates every violation
    rather than collapsing them into a single ambiguous message.
    """
    if not ctx.file.package:
        return
    for segment in ctx.file.package.split("."):
        if not _SNAKE_CASE_RE.match(segment):
            ctx.emit(
                violation_kind="naming/snake-case-packages",
                params={"package": ctx.file.package, "segment": segment},
            )


# Module-level RULES tuple — same attribute name as compat
# (``schema/checker.py:217-220``) but holding bare decorated callables,
# not (rule_id, fn) tuples. ``LintEngine.load_rule_pack`` reads this
# attribute and extracts each fn's ``_lint_spec``.
RULES: tuple[Callable[..., None], ...] = (
    check_snake_case_fields,
    check_pascal_case_messages,
    check_pascal_case_enums,
    check_upper_snake_case_enum_values,
    check_snake_case_oneofs,
    check_pascal_case_services,
    check_pascal_case_rpcs,
    check_snake_case_files,
    check_snake_case_packages,
)
